backend:
  name: github
  repo: punggolzenith/januarythyn
  branch: master
media_folder: .vuepress/public/img/uploads
public_folder: .vuepress/public
display_url: https://suspicious-visvesvaraya-5459d7.netlify.app/
collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/blog
    label: "docs" # Used in the UI
    folder: "lessons" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    show_preview_links: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
